AppGestionEMS/Controllers/AsignaciónDocentesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppGestionEMS.Models;

namespace AppGestionEMS.Controllers
{
    [Authorize(Roles = "admin")]
    public class AsignaciónDocentesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AsignaciónDocentes
        public ActionResult Index()
        {
            var asignaciónDocentes = db.AsignaciónDocentes.Include(a => a.Curso).Include(a => a.Grupo).Include(a => a.User);
            return View(asignaciónDocentes.ToList());
        }


        // GET: AsignaciónDocentes/Create
        public ActionResult Create()
        {
            var profesores = from user in db.Users
                             from u_r in user.Roles
                             join rol in db.Roles on u_r.RoleId equals rol.Id
                             where rol.Name == "profesor"
                             select user.Nombre;

            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "actual");
            ViewBag.GrupoId = new SelectList(db.Grupos, "Id", "nombre");
            ViewBag.UserId = new SelectList(db.Users.Where(u => profesores.Contains(u.Nombre)), "Id", "Nombre");
            return View();
        }

        // POST: AsignaciónDocentes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,CursoId,GrupoId,fecha")] AsignaciónDocentes asignaciónDocentes)
        {
            if (ModelState.IsValid)
            {
                db.AsignaciónDocentes.Add(asignaciónDocentes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "actual", asignaciónDocentes.CursoId);
            ViewBag.GrupoId = new SelectList(db.Grupos, "Id", "nombre", asignaciónDocentes.GrupoId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Nombre", asignaciónDocentes.UserId);
            return View(asignaciónDocentes);
        }

        
        // GET: AsignaciónDocentes/Delete/5
        public ActionResult Delete(int? curso, int? grupo, string user)
        {
            if (curso == null || grupo == null || user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AsignaciónDocentes asignaciónDocentes = db.AsignaciónDocentes.Find(user, curso, grupo);
            if (asignaciónDocentes == null)
            {
                return HttpNotFound();
            }
            return View(asignaciónDocentes);
        }

        // POST: AsignaciónDocentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int curso, int grupo, string user)
        {
            AsignaciónDocentes asignaciónDocentes = db.AsignaciónDocentes.Find(user, curso, grupo);
            db.AsignaciónDocentes.Remove(asignaciónDocentes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppGestionEMS/Controllers/MatriculasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppGestionEMS.Models;

namespace AppGestionEMS.Controllers
{
    [Authorize(Roles = "admin, profesor")]
    public class MatriculasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Matriculas
        public ActionResult Index()
        {
            var matriculas = db.Matriculas.Include(m => m.Curso).Include(m => m.Grupo).Include(m => m.User);
            return View(matriculas.ToList());
        }


        // GET: Matriculas/Create
        public ActionResult Create()
        {
            var alumnos = from user in db.Users
                          from u_r in user.Roles
                          join rol in db.Roles on u_r.RoleId equals rol.Id
                          where rol.Name == "alumno"
                          select user.Nombre;

            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "actual");
            ViewBag.GrupoId = new SelectList(db.Grupos, "Id", "nombre");
            ViewBag.UserId = new SelectList(db.Users.Where(u => alumnos.Contains(u.Nombre)), "Id", "Nombre");
            return View();
        }

        // POST: Matriculas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,CursoId,GrupoId,fecha")] Matriculas matriculas)
        {
            if (ModelState.IsValid)
            {
                db.Matriculas.Add(matriculas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "actual", matriculas.CursoId);
            ViewBag.GrupoId = new SelectList(db.Grupos, "Id", "nombre", matriculas.GrupoId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Nombre", matriculas.UserId);
            return View(matriculas);
        }

        // GET: Matriculas/Delete/5
        public ActionResult Delete(int? curso, int? grupo, string user)
        {
            if (curso == null || grupo == null || user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matriculas matriculas = db.Matriculas.Find(user, curso, grupo);
            if (matriculas == null)
            {
                return HttpNotFound();
            }
            return View(matriculas);
        }

        // POST: Matriculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int curso, int grupo, string user)
        {
            Matriculas matriculas = db.Matriculas.Find(user, curso, grupo);
            db.Matriculas.Remove(matriculas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppGestionEMS/Controllers/MisEvaluacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppGestionEMS.Models;
using Microsoft.AspNet.Identity;

namespace AppGestionEMS.Controllers
{
    [Authorize(Roles = "alumno")]
    public class MisEvaluacionesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MisEvaluaciones
        public ActionResult Index()
        {
            string currentUserId = User.Identity.GetUserId();
            var evaluaciones = db.Evaluaciones.Include(e => e.Curso).Include(e => e.User).Where(p => p.UserId == currentUserId);
            return View(evaluaciones.ToList());
        }

        // GET: MisEvaluaciones/Details/5
        public ActionResult Details(int? curso, string user)
        {
            if (curso == null || user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evaluaciones evaluaciones = db.Evaluaciones.Find(user, curso);
            if (evaluaciones == null)
            {
                return HttpNotFound();
            }
            return View(evaluaciones);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppGestionEMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style = "background-color: #B8D5F1;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GestAsig", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cursos", "Index", "Cursos")</li>
                    <li>@Html.ActionLink("Grupos", "Index", "Grupos")</li>
                    <li>@Html.ActionLink("Asignación Docente", "Index", "AsignaciónDocentes")</li>
                    <li>@Html.ActionLink("Matriculación", "Index", "Matriculas")</li>
                    <li>@Html.ActionLink("Evaluaciones", "Index", "Evaluaciones")</li>
                    <li>@Html.ActionLink("Mis Evaluaciones", "Index", "MisEvaluaciones")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Gestión de Asignaturas</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>